name: assay_correlations
channels:
    - bioconda
    - conda-forge
    - https://repo.anaconda.com/pkgs/free/linux-64
    - https://repo.anaconda.com/pkgs/free/noarch
    - https://repo.anaconda.com/pkgs/pro/linux-64
    - https://repo.anaconda.com/pkgs/pro/noarch
    - nodefaults

dependencies:
    - snakemake=5.3.0
    - gawk=4.2.1
    - sed=4.4
    - bedtools=2.27.1
    - pyfaidx=0.5.4.1
    - r-tidyverse=1.1.1
    - r-stringi=1.1.7
    - r-svglite=1.2.1
    - r-gdtools=0.1.6
    - r-ggally=1.3.2
    - r-hexbin=1.27.2
    - r-viridis=0.4.0
    - svg2png=4.1.1

